import type { InsertMonsterSpecies } from "@workspace/db";

export const MONSTER_SEED_DATA: InsertMonsterSpecies[] = [
  // ====== FIRE ======
  {
    id: "ember-drake",
    name: "Ember Drake",
    element: "Fire",
    rarity: "Common",
    baseHp: 45,
    baseAttack: 52,
    baseDefense: 38,
    baseSpeed: 55,
    description: "A small lizard with glowing embers along its spine.",
    lore: "Found near volcanic vents, Ember Drakes are attracted to heat and light. Ancient people thought they were sparks that gained consciousness.",
    personality: "Brave",
    weight: 8.5,
    height: 0.6,
    captureRate: 85,
    evolutionFromId: null,
    evolutionToId: "lava-horn",
    evolutionLevel: 16,
    skills: [
      { name: "Ember Bite", type: "normal", element: "Fire", power: 40, accuracy: 95, description: "A heated bite that singes the target." },
      { name: "Flame Burst", type: "skill1", element: "Fire", power: 65, accuracy: 90, description: "Exhales a concentrated burst of flame." },
      { name: "Heat Wave", type: "skill2", element: "Fire", power: 80, accuracy: 80, description: "Releases a scorching wave of heat." },
      { name: "Inferno Roar", type: "ultimate", element: "Fire", power: 120, accuracy: 75, description: "A terrifying roar that engulfs the area in flames." },
      { name: "Ember Shield", type: "passive", element: "Fire", power: 0, accuracy: 100, description: "Reduces Fire damage received by 20%." },
    ],
    regionIds: ["volcanic-rift", "lava-caves"],
  },
  {
    id: "lava-horn",
    name: "Lava Horn",
    element: "Fire",
    rarity: "Uncommon",
    baseHp: 70,
    baseAttack: 78,
    baseDefense: 60,
    baseSpeed: 48,
    description: "A powerful drake with horns that drip molten rock.",
    lore: "When a Lava Horn charges, the ground itself melts beneath its hooves. Volcano dwellers mark their territories by the scorch marks these creatures leave.",
    personality: "Fierce",
    weight: 95,
    height: 1.4,
    captureRate: 55,
    evolutionFromId: "ember-drake",
    evolutionToId: null,
    evolutionLevel: null,
    skills: [
      { name: "Magma Stomp", type: "normal", element: "Fire", power: 55, accuracy: 95, description: "Stomps the ground, sending magma splashing." },
      { name: "Horn Blaze", type: "skill1", element: "Fire", power: 80, accuracy: 88, description: "Charges with blazing horn, dealing heavy damage." },
      { name: "Lava Geyser", type: "skill2", element: "Earth", power: 85, accuracy: 80, description: "Opens a lava geyser beneath the target." },
      { name: "Volcanic Fury", type: "ultimate", element: "Fire", power: 150, accuracy: 70, description: "Unleashes the rage of a volcano in one devastating strike." },
      { name: "Molten Core", type: "passive", element: "Fire", power: 0, accuracy: 100, description: "Burns attackers when taking physical damage." },
    ],
    regionIds: ["volcanic-rift", "lava-caves"],
  },
  {
    id: "pyro-fox",
    name: "Pyro Fox",
    element: "Fire",
    rarity: "Rare",
    baseHp: 58,
    baseAttack: 88,
    baseDefense: 45,
    baseSpeed: 95,
    description: "A sleek fire fox with nine blazing tails.",
    lore: "Pyro Foxes are tricksters who lure travelers with illusions of campfire warmth, then vanish into the flames. They are considered lucky omens in some cultures.",
    personality: "Cunning",
    weight: 19.5,
    height: 0.9,
    captureRate: 30,
    evolutionFromId: null,
    evolutionToId: null,
    evolutionLevel: null,
    skills: [
      { name: "Fire Dash", type: "normal", element: "Fire", power: 50, accuracy: 100, description: "Dashes through the target at blinding speed." },
      { name: "Tail Whip", type: "skill1", element: "Fire", power: 70, accuracy: 95, description: "Whips multiple fire tails across the target." },
      { name: "Fox Fire", type: "skill2", element: "Fire", power: 90, accuracy: 85, description: "Creates illusory flames that disorient and burn." },
      { name: "Nine Flame Dance", type: "ultimate", element: "Fire", power: 160, accuracy: 70, description: "All nine tails spiral into a vortex of fire." },
      { name: "Quick Step", type: "passive", element: "Fire", power: 0, accuracy: 100, description: "Increases evasion by 15% after each move." },
    ],
    regionIds: ["volcanic-rift"],
  },
  // ====== WATER ======
  {
    id: "aquafin",
    name: "Aquafin",
    element: "Water",
    rarity: "Common",
    baseHp: 50,
    baseAttack: 42,
    baseDefense: 50,
    baseSpeed: 60,
    description: "A small water creature with crystalline fins.",
    lore: "Aquafins are abundant in coastal waters. Their fins change color with their mood — blue for calm, green for playful, red for threatened.",
    personality: "Gentle",
    weight: 12,
    height: 0.5,
    captureRate: 90,
    evolutionFromId: null,
    evolutionToId: "tide-walker",
    evolutionLevel: 14,
    skills: [
      { name: "Water Jet", type: "normal", element: "Water", power: 38, accuracy: 98, description: "A precise jet of water aimed at the target." },
      { name: "Bubble Burst", type: "skill1", element: "Water", power: 60, accuracy: 92, description: "Fires a barrage of pressurized bubbles." },
      { name: "Tidal Pull", type: "skill2", element: "Water", power: 75, accuracy: 85, description: "Creates a tidal force that batters the foe." },
      { name: "Maelstrom", type: "ultimate", element: "Water", power: 125, accuracy: 75, description: "Summons a miniature maelstrom around the target." },
      { name: "Slick Scales", type: "passive", element: "Water", power: 0, accuracy: 100, description: "Reduces physical damage by 10% due to slippery scales." },
    ],
    regionIds: ["ocean-ruins", "shadow-marsh"],
  },
  {
    id: "tide-walker",
    name: "Tide Walker",
    element: "Water",
    rarity: "Uncommon",
    baseHp: 78,
    baseAttack: 65,
    baseDefense: 80,
    baseSpeed: 42,
    description: "A crustacean monster that walks between sea and land.",
    lore: "Tide Walkers emerge from the ocean at high tide, leaving behind ancient ruins as they pass. They are said to be living compasses for lost sailors.",
    personality: "Steadfast",
    weight: 85,
    height: 1.2,
    captureRate: 50,
    evolutionFromId: "aquafin",
    evolutionToId: null,
    evolutionLevel: null,
    skills: [
      { name: "Claw Crush", type: "normal", element: "Water", power: 52, accuracy: 95, description: "Crushes with powerful pincers." },
      { name: "Tidal Slam", type: "skill1", element: "Water", power: 78, accuracy: 88, description: "Slams with the force of an ocean wave." },
      { name: "Shell Guard", type: "skill2", element: "Water", power: 0, accuracy: 100, description: "Retreats into shell, greatly boosting defense." },
      { name: "Ocean Surge", type: "ultimate", element: "Water", power: 145, accuracy: 72, description: "Channels the entire ocean's power into one surge." },
      { name: "Hardshell", type: "passive", element: "Water", power: 0, accuracy: 100, description: "Defense is boosted by 25% when HP drops below 50%." },
    ],
    regionIds: ["ocean-ruins"],
  },
  {
    id: "storm-eel",
    name: "Storm Eel",
    element: "Electric",
    rarity: "Rare",
    baseHp: 62,
    baseAttack: 90,
    baseDefense: 42,
    baseSpeed: 88,
    description: "A serpentine eel crackling with storm energy.",
    lore: "Storm Eels are the bane of sailors. They generate enough electricity to power a small village for a week, and often call lightning storms by raising their antenna fins.",
    personality: "Volatile",
    weight: 22,
    height: 1.8,
    captureRate: 28,
    evolutionFromId: null,
    evolutionToId: null,
    evolutionLevel: null,
    skills: [
      { name: "Shock Bite", type: "normal", element: "Electric", power: 48, accuracy: 98, description: "Bites with electrified fangs." },
      { name: "Thunder Coil", type: "skill1", element: "Electric", power: 75, accuracy: 90, description: "Coils around the target, discharging electricity." },
      { name: "Storm Surge", type: "skill2", element: "Water", power: 82, accuracy: 82, description: "Combines water and lightning in a devastating surge." },
      { name: "Lightning Rod Fury", type: "ultimate", element: "Electric", power: 155, accuracy: 68, description: "Calls a bolt of pure lightning from the storm clouds." },
      { name: "Charged Body", type: "passive", element: "Electric", power: 0, accuracy: 100, description: "Paralyzes attackers with static charge on contact." },
    ],
    regionIds: ["ocean-ruins", "thunder-valley"],
  },
  // ====== NATURE ======
  {
    id: "leafhorn",
    name: "Leafhorn",
    element: "Nature",
    rarity: "Common",
    baseHp: 55,
    baseAttack: 48,
    baseDefense: 55,
    baseSpeed: 50,
    description: "A small deer-like creature with leaf-shaped antlers.",
    lore: "Leafhorns are the caretakers of ancient forests. Where they graze, flowers bloom within hours. Cutting down a tree near a Leafhorn is considered deeply unlucky.",
    personality: "Gentle",
    weight: 35,
    height: 0.9,
    captureRate: 88,
    evolutionFromId: null,
    evolutionToId: "thorn-boar",
    evolutionLevel: 18,
    skills: [
      { name: "Vine Lash", type: "normal", element: "Nature", power: 40, accuracy: 97, description: "Whips the target with razor-sharp vines." },
      { name: "Petal Storm", type: "skill1", element: "Nature", power: 62, accuracy: 90, description: "Sends razor petals spiraling at the target." },
      { name: "Root Bind", type: "skill2", element: "Nature", power: 72, accuracy: 85, description: "Erupts roots from the earth, binding and crushing." },
      { name: "Ancient Bloom", type: "ultimate", element: "Nature", power: 130, accuracy: 73, description: "Channels the life force of an ancient forest." },
      { name: "Forest Guard", type: "passive", element: "Nature", power: 0, accuracy: 100, description: "Heals 5% of max HP per turn while in Nature terrain." },
    ],
    regionIds: ["verdant-meadows", "ancient-forest"],
  },
  {
    id: "thorn-boar",
    name: "Thorn Boar",
    element: "Nature",
    rarity: "Uncommon",
    baseHp: 88,
    baseAttack: 72,
    baseDefense: 70,
    baseSpeed: 38,
    description: "A heavily armored boar covered in poisonous thorns.",
    lore: "Thorn Boars are the most aggressive herbivores in the known world. Their hide is so tough that even iron weapons bounce off. Hunters avoid them entirely.",
    personality: "Aggressive",
    weight: 110,
    height: 1.3,
    captureRate: 48,
    evolutionFromId: "leafhorn",
    evolutionToId: null,
    evolutionLevel: null,
    skills: [
      { name: "Thorn Charge", type: "normal", element: "Nature", power: 58, accuracy: 93, description: "Charges with thorn-covered hide, piercing all defenses." },
      { name: "Poison Spike", type: "skill1", element: "Nature", power: 72, accuracy: 87, description: "Launches venomous thorns at the target." },
      { name: "Wild Stomp", type: "skill2", element: "Earth", power: 88, accuracy: 80, description: "Stomps the ground with earth-shaking force." },
      { name: "Briar Fury", type: "ultimate", element: "Nature", power: 148, accuracy: 70, description: "Explodes in a frenzy of thorns and wild nature energy." },
      { name: "Thorn Armor", type: "passive", element: "Nature", power: 0, accuracy: 100, description: "Returns 15% of physical damage to attacker." },
    ],
    regionIds: ["verdant-meadows", "ancient-forest"],
  },
  {
    id: "vine-golem",
    name: "Vine Golem",
    element: "Nature",
    rarity: "Epic",
    baseHp: 110,
    baseAttack: 82,
    baseDefense: 98,
    baseSpeed: 28,
    description: "A colossal entity formed from ancient vines and sentient roots.",
    lore: "Vine Golems are formed when a forest has been wounded by fire or deforestation. The land's grief coalesces into a guardian that destroys all threats for centuries.",
    personality: "Resolute",
    weight: 850,
    height: 4.2,
    captureRate: 10,
    evolutionFromId: null,
    evolutionToId: null,
    evolutionLevel: null,
    skills: [
      { name: "Root Slam", type: "normal", element: "Nature", power: 65, accuracy: 92, description: "Slams with a massive root tendril." },
      { name: "Entangle", type: "skill1", element: "Nature", power: 78, accuracy: 88, description: "Wraps the target in strangling vines." },
      { name: "Overgrowth", type: "skill2", element: "Nature", power: 100, accuracy: 78, description: "Summons explosive growth that overwhelms the target." },
      { name: "Forest Collapse", type: "ultimate", element: "Nature", power: 175, accuracy: 65, description: "Collapses an entire section of forest onto the target." },
      { name: "Regrowth", type: "passive", element: "Nature", power: 0, accuracy: 100, description: "Regenerates 8% of max HP each turn." },
    ],
    regionIds: ["ancient-forest"],
  },
  // ====== ELECTRIC ======
  {
    id: "volt-lynx",
    name: "Volt Lynx",
    element: "Electric",
    rarity: "Common",
    baseHp: 48,
    baseAttack: 58,
    baseDefense: 40,
    baseSpeed: 72,
    description: "A nimble cat-like creature bristling with static electricity.",
    lore: "Volt Lynxes are drawn to power lines and electrical storms. Their purring generates a constant electric hum, and they can discharge bolts from their whiskers.",
    personality: "Playful",
    weight: 14,
    height: 0.7,
    captureRate: 82,
    evolutionFromId: null,
    evolutionToId: "thunder-raven",
    evolutionLevel: 20,
    skills: [
      { name: "Static Pounce", type: "normal", element: "Electric", power: 42, accuracy: 97, description: "Pounces with a static-charged body." },
      { name: "Spark Fang", type: "skill1", element: "Electric", power: 65, accuracy: 92, description: "Bites with electrically-charged fangs." },
      { name: "Volt Dash", type: "skill2", element: "Electric", power: 78, accuracy: 88, description: "Dashes at lightning speed, leaving an electric trail." },
      { name: "Thunder Claws", type: "ultimate", element: "Electric", power: 135, accuracy: 72, description: "Slashes with claws channeling pure lightning." },
      { name: "Speed Charge", type: "passive", element: "Electric", power: 0, accuracy: 100, description: "Gains +10% speed for each successive attack that hits." },
    ],
    regionIds: ["thunder-valley", "power-plant"],
  },
  {
    id: "thunder-raven",
    name: "Thunder Raven",
    element: "Electric",
    rarity: "Uncommon",
    baseHp: 65,
    baseAttack: 82,
    baseDefense: 52,
    baseSpeed: 90,
    description: "A storm bird that rides lightning bolts between clouds.",
    lore: "Thunder Ravens are messengers of the storm. Ancient cultures believed they carried the gods' lightning. Their wingspan can block out the sun in an instant.",
    personality: "Proud",
    weight: 8,
    height: 1.1,
    captureRate: 45,
    evolutionFromId: "volt-lynx",
    evolutionToId: null,
    evolutionLevel: null,
    skills: [
      { name: "Wing Bolt", type: "normal", element: "Electric", power: 55, accuracy: 97, description: "Slices with electrified wings." },
      { name: "Thunderstrike", type: "skill1", element: "Electric", power: 82, accuracy: 88, description: "Calls down a focused thunderbolt." },
      { name: "Storm Dive", type: "skill2", element: "Air", power: 88, accuracy: 83, description: "Dives at extreme speed through a storm." },
      { name: "Tempest Fury", type: "ultimate", element: "Electric", power: 155, accuracy: 70, description: "Unleashes a fully formed tempest in concentrated form." },
      { name: "Storm Sense", type: "passive", element: "Electric", power: 0, accuracy: 100, description: "Always attacks first in storms. +20% accuracy." },
    ],
    regionIds: ["thunder-valley"],
  },
  // ====== ICE ======
  {
    id: "frost-bear",
    name: "Frost Bear",
    element: "Ice",
    rarity: "Common",
    baseHp: 68,
    baseAttack: 55,
    baseDefense: 62,
    baseSpeed: 38,
    description: "A bear coated in permanent ice crystals.",
    lore: "Frost Bears sleep through summer and emerge in the first snowfall. Their breath alone can freeze a river solid. Explorers give them a wide berth.",
    personality: "Stoic",
    weight: 180,
    height: 1.8,
    captureRate: 78,
    evolutionFromId: null,
    evolutionToId: "crystal-wolf",
    evolutionLevel: 15,
    skills: [
      { name: "Frost Swipe", type: "normal", element: "Ice", power: 45, accuracy: 95, description: "Swipes with ice-coated claws." },
      { name: "Blizzard Breath", type: "skill1", element: "Ice", power: 68, accuracy: 88, description: "Exhales a torrent of freezing air." },
      { name: "Glacier Slam", type: "skill2", element: "Ice", power: 85, accuracy: 80, description: "Leaps and slams down with glacial force." },
      { name: "Permafrost Roar", type: "ultimate", element: "Ice", power: 132, accuracy: 72, description: "A roar that drops the temperature to absolute zero in a radius." },
      { name: "Ice Coat", type: "passive", element: "Ice", power: 0, accuracy: 100, description: "Ice armor provides 15% damage reduction against Fire attacks." },
    ],
    regionIds: ["frozen-mountain"],
  },
  {
    id: "crystal-wolf",
    name: "Crystal Wolf",
    element: "Crystal",
    rarity: "Rare",
    baseHp: 72,
    baseAttack: 88,
    baseDefense: 75,
    baseSpeed: 82,
    description: "A wolf whose body is made entirely of living crystal.",
    lore: "Crystal Wolves are born in the deepest caverns where light never reaches, yet their bodies glow with inner radiance. They hunt by detecting vibrations through their crystalline paws.",
    personality: "Mysterious",
    weight: 42,
    height: 1.2,
    captureRate: 25,
    evolutionFromId: "frost-bear",
    evolutionToId: null,
    evolutionLevel: null,
    skills: [
      { name: "Crystal Fang", type: "normal", element: "Crystal", power: 52, accuracy: 95, description: "Bites with razor-sharp crystal teeth." },
      { name: "Prism Howl", type: "skill1", element: "Crystal", power: 78, accuracy: 88, description: "A howl that shatters reality into prismatic shards." },
      { name: "Refraction Strike", type: "skill2", element: "Light", power: 88, accuracy: 82, description: "Refracts light into a focused cutting beam." },
      { name: "Crystal Nova", type: "ultimate", element: "Crystal", power: 162, accuracy: 68, description: "Explodes outward in an expanding sphere of crystal shards." },
      { name: "Crystalline", type: "passive", element: "Crystal", power: 0, accuracy: 100, description: "Reflects 20% of special damage back to attacker." },
    ],
    regionIds: ["crystal-caverns", "frozen-mountain"],
  },
  {
    id: "glacier-drake",
    name: "Glacier Drake",
    element: "Ice",
    rarity: "Epic",
    baseHp: 105,
    baseAttack: 92,
    baseDefense: 95,
    baseSpeed: 45,
    description: "A massive drake whose wings are frozen solid with ancient ice.",
    lore: "Glacier Drakes have wings that carry the memory of ten thousand winters. The ice within them contains air bubbles from before recorded history, which scientists would pay fortunes to study.",
    personality: "Ancient",
    weight: 720,
    height: 5.5,
    captureRate: 8,
    evolutionFromId: null,
    evolutionToId: null,
    evolutionLevel: null,
    skills: [
      { name: "Frozen Wing", type: "normal", element: "Ice", power: 65, accuracy: 93, description: "Slashes with a massive frozen wing." },
      { name: "Absolute Zero", type: "skill1", element: "Ice", power: 95, accuracy: 82, description: "Drops the temperature instantly, freezing solid." },
      { name: "Ancient Frost", type: "skill2", element: "Ice", power: 108, accuracy: 75, description: "Unleashes ice older than civilization itself." },
      { name: "Blizzard Reign", type: "ultimate", element: "Ice", power: 178, accuracy: 62, description: "Calls a continent-scale blizzard into concentrated form." },
      { name: "Ice Age", type: "passive", element: "Ice", power: 0, accuracy: 100, description: "All enemies lose 5% HP at the start of each turn from the cold." },
    ],
    regionIds: ["frozen-mountain"],
  },
  // ====== EARTH ======
  {
    id: "stoneback",
    name: "Stoneback",
    element: "Earth",
    rarity: "Common",
    baseHp: 62,
    baseAttack: 48,
    baseDefense: 72,
    baseSpeed: 30,
    description: "A tortoise-like creature with a shell made of living rock.",
    lore: "Stonebacks are among the oldest species alive. Geologists have found Stoneback shells embedded in strata millions of years old, identical to modern specimens.",
    personality: "Patient",
    weight: 220,
    height: 0.8,
    captureRate: 80,
    evolutionFromId: null,
    evolutionToId: "boulder-ram",
    evolutionLevel: 16,
    skills: [
      { name: "Rock Bash", type: "normal", element: "Earth", power: 42, accuracy: 95, description: "Bashes with a rock-hard head." },
      { name: "Stone Spit", type: "skill1", element: "Earth", power: 65, accuracy: 90, description: "Fires sharpened stones from its mouth." },
      { name: "Earthquake", type: "skill2", element: "Earth", power: 82, accuracy: 82, description: "Creates a localized earthquake." },
      { name: "Continental Crush", type: "ultimate", element: "Earth", power: 135, accuracy: 72, description: "Focuses the weight of a continent into a single attack." },
      { name: "Rock Solid", type: "passive", element: "Earth", power: 0, accuracy: 100, description: "Takes 20% less damage from all attacks." },
    ],
    regionIds: ["desert", "verdant-meadows"],
  },
  {
    id: "sand-lurker",
    name: "Sand Lurker",
    element: "Earth",
    rarity: "Rare",
    baseHp: 70,
    baseAttack: 92,
    baseDefense: 55,
    baseSpeed: 78,
    description: "A predator that hides under desert sand, striking without warning.",
    lore: "Sand Lurkers are the apex predators of desert biomes. They create sand funnels to trap prey, then erupt upward with shocking speed. Their ambushes are almost unavoidable.",
    personality: "Cunning",
    weight: 55,
    height: 1.5,
    captureRate: 28,
    evolutionFromId: null,
    evolutionToId: null,
    evolutionLevel: null,
    skills: [
      { name: "Sand Strike", type: "normal", element: "Earth", power: 52, accuracy: 95, description: "Erupts from sand to strike the target." },
      { name: "Desert Fang", type: "skill1", element: "Earth", power: 78, accuracy: 88, description: "Lunges with venomous earth-infused fangs." },
      { name: "Sand Storm", type: "skill2", element: "Earth", power: 85, accuracy: 80, description: "Creates a blinding, cutting sandstorm." },
      { name: "Quicksand Trap", type: "ultimate", element: "Earth", power: 158, accuracy: 68, description: "Encases the target in rapidly hardening sand." },
      { name: "Ambush", type: "passive", element: "Earth", power: 0, accuracy: 100, description: "First strike each battle deals 50% bonus damage." },
    ],
    regionIds: ["desert"],
  },
  // ====== DARK ======
  {
    id: "night-stalker",
    name: "Night Stalker",
    element: "Dark",
    rarity: "Common",
    baseHp: 52,
    baseAttack: 60,
    baseDefense: 42,
    baseSpeed: 68,
    description: "A wolf-like creature that blends perfectly into darkness.",
    lore: "Night Stalkers are never seen before they strike. They absorb all light around them, creating pockets of absolute darkness. Their howl is said to drain the courage from any who hear it.",
    personality: "Solitary",
    weight: 48,
    height: 1.0,
    captureRate: 82,
    evolutionFromId: null,
    evolutionToId: "shadow-moth",
    evolutionLevel: 18,
    skills: [
      { name: "Shadow Bite", type: "normal", element: "Dark", power: 45, accuracy: 95, description: "Bites from a shadow that cannot be tracked." },
      { name: "Dark Pulse", type: "skill1", element: "Dark", power: 68, accuracy: 90, description: "Releases a wave of dark energy." },
      { name: "Void Howl", type: "skill2", element: "Dark", power: 80, accuracy: 82, description: "A howl that creates a zone of absolute darkness." },
      { name: "Null Zone", type: "ultimate", element: "Dark", power: 138, accuracy: 72, description: "Creates a zone where all energy is absorbed into nothingness." },
      { name: "Shadow Step", type: "passive", element: "Dark", power: 0, accuracy: 100, description: "Has 20% chance to dodge any attack by stepping into shadow." },
    ],
    regionIds: ["shadow-marsh", "dark-forest"],
  },
  {
    id: "shadow-moth",
    name: "Shadow Moth",
    element: "Dark",
    rarity: "Uncommon",
    baseHp: 58,
    baseAttack: 72,
    baseDefense: 48,
    baseSpeed: 85,
    description: "A moth with wings that absorb all light they touch.",
    lore: "Shadow Moths are believed to be fragments of the void that took physical form. When a Shadow Moth's wing beats near a flame, the flame dims as if afraid.",
    personality: "Eerie",
    weight: 3,
    height: 0.8,
    captureRate: 50,
    evolutionFromId: "night-stalker",
    evolutionToId: null,
    evolutionLevel: null,
    skills: [
      { name: "Dust Strike", type: "normal", element: "Dark", power: 50, accuracy: 97, description: "Releases dark scales that steal energy." },
      { name: "Void Wings", type: "skill1", element: "Dark", power: 75, accuracy: 88, description: "Wraps the target in lightless wing shadow." },
      { name: "Dream Drain", type: "skill2", element: "Dark", power: 88, accuracy: 82, description: "Drains the target's will to fight." },
      { name: "Eternal Darkness", type: "ultimate", element: "Dark", power: 152, accuracy: 70, description: "Smothers the target in a shroud of eternal void." },
      { name: "Light Absorption", type: "passive", element: "Dark", power: 0, accuracy: 100, description: "Light-based attacks heal instead of damage." },
    ],
    regionIds: ["shadow-marsh"],
  },
  {
    id: "void-crawler",
    name: "Void Crawler",
    element: "Void",
    rarity: "Rare",
    baseHp: 68,
    baseAttack: 85,
    baseDefense: 58,
    baseSpeed: 75,
    description: "A spider-like entity that exists partially between dimensions.",
    lore: "Void Crawlers are not fully in this world. Their movements seem to violate physics — they can appear behind obstacles they never passed through. Capturing one is considered a major feat.",
    personality: "Alien",
    weight: 18,
    height: 0.9,
    captureRate: 22,
    evolutionFromId: null,
    evolutionToId: null,
    evolutionLevel: null,
    skills: [
      { name: "Phase Fang", type: "normal", element: "Void", power: 55, accuracy: 95, description: "Bites through dimensional barriers." },
      { name: "Rift Web", type: "skill1", element: "Void", power: 78, accuracy: 87, description: "Webs made of dimensional tears entangle the foe." },
      { name: "Dimension Slash", type: "skill2", element: "Void", power: 92, accuracy: 78, description: "Slashes through reality itself." },
      { name: "Void Collapse", type: "ultimate", element: "Void", power: 165, accuracy: 65, description: "Collapses a localized void around the target." },
      { name: "Phase Shift", type: "passive", element: "Void", power: 0, accuracy: 100, description: "Randomly phases out of existence, dodging 15% of attacks." },
    ],
    regionIds: ["ancient-temple", "shadow-marsh"],
  },
  // ====== LIGHT ======
  {
    id: "dawn-hawk",
    name: "Dawn Hawk",
    element: "Light",
    rarity: "Common",
    baseHp: 50,
    baseAttack: 60,
    baseDefense: 42,
    baseSpeed: 78,
    description: "A hawk that always flies toward the rising sun.",
    lore: "Dawn Hawks were sacred birds in ancient sun-worshiping civilizations. They migrate thousands of miles each year following the sunrise, never once flying in darkness.",
    personality: "Noble",
    weight: 4,
    height: 0.7,
    captureRate: 85,
    evolutionFromId: null,
    evolutionToId: "solar-wyrm",
    evolutionLevel: 22,
    skills: [
      { name: "Light Strike", type: "normal", element: "Light", power: 42, accuracy: 98, description: "Slashes with a wing of pure light." },
      { name: "Radiant Dive", type: "skill1", element: "Light", power: 68, accuracy: 90, description: "Dives with blinding radiance." },
      { name: "Solar Flare", type: "skill2", element: "Light", power: 82, accuracy: 82, description: "Releases a blinding solar flare." },
      { name: "Dawn Break", type: "ultimate", element: "Light", power: 138, accuracy: 72, description: "Channels the power of a sunrise into a devastating beam." },
      { name: "Blessing of Dawn", type: "passive", element: "Light", power: 0, accuracy: 100, description: "Restores 8% HP at the start of each turn during day hours." },
    ],
    regionIds: ["sky-islands", "ancient-temple"],
  },
  {
    id: "solar-wyrm",
    name: "Solar Wyrm",
    element: "Light",
    rarity: "Epic",
    baseHp: 98,
    baseAttack: 105,
    baseDefense: 80,
    baseSpeed: 70,
    description: "A serpentine creature that orbits the sun during its sleep cycle.",
    lore: "Solar Wyrms are visible from the ground as bright streaks across the sky during sunrise and sunset. They absorb solar energy while airborne and release it in catastrophic bursts.",
    personality: "Magnificent",
    weight: 380,
    height: 8.0,
    captureRate: 6,
    evolutionFromId: "dawn-hawk",
    evolutionToId: null,
    evolutionLevel: null,
    skills: [
      { name: "Solar Bite", type: "normal", element: "Light", power: 68, accuracy: 93, description: "Bites with sun-heated fangs." },
      { name: "Supernova", type: "skill1", element: "Light", power: 102, accuracy: 82, description: "Triggers a miniature supernova burst." },
      { name: "Plasma Stream", type: "skill2", element: "Light", power: 115, accuracy: 75, description: "Fires a stream of stellar plasma." },
      { name: "Solar Annihilation", type: "ultimate", element: "Light", power: 200, accuracy: 58, description: "Focuses the entire output of the sun into one instant of destruction." },
      { name: "Stellar Aura", type: "passive", element: "Light", power: 0, accuracy: 100, description: "Burns nearby enemies for 8% of their max HP each turn." },
    ],
    regionIds: ["sky-islands", "ancient-temple"],
  },
  // ====== CRYSTAL ======
  {
    id: "prism-gecko",
    name: "Prism Gecko",
    element: "Crystal",
    rarity: "Common",
    baseHp: 48,
    baseAttack: 52,
    baseDefense: 58,
    baseSpeed: 62,
    description: "A gecko with scales that split light into rainbows.",
    lore: "Prism Geckos cling to cave ceilings, using their scales to redirect bioluminescent fungi light. Crystal miners consider them good luck; finding one means rich crystal deposits are nearby.",
    personality: "Curious",
    weight: 1.2,
    height: 0.3,
    captureRate: 88,
    evolutionFromId: null,
    evolutionToId: "facet-crab",
    evolutionLevel: 14,
    skills: [
      { name: "Crystal Lick", type: "normal", element: "Crystal", power: 38, accuracy: 98, description: "A crystalline tongue slap that disorients." },
      { name: "Prism Beam", type: "skill1", element: "Light", power: 62, accuracy: 93, description: "Refracts light into a focused damaging beam." },
      { name: "Shard Scatter", type: "skill2", element: "Crystal", power: 75, accuracy: 88, description: "Scatters razor crystal shards." },
      { name: "Rainbow Prism", type: "ultimate", element: "Crystal", power: 128, accuracy: 75, description: "Creates a full-spectrum prism blast of pure crystal energy." },
      { name: "Refract", type: "passive", element: "Crystal", power: 0, accuracy: 100, description: "Light-element attacks deal 25% less damage." },
    ],
    regionIds: ["crystal-caverns"],
  },
  {
    id: "facet-crab",
    name: "Facet Crab",
    element: "Crystal",
    rarity: "Uncommon",
    baseHp: 75,
    baseAttack: 68,
    baseDefense: 88,
    baseSpeed: 35,
    description: "A crab encased in perfectly faceted crystal armor.",
    lore: "Facet Crabs shed their crystal shells annually, leaving behind perfect geometric sculptures that sell for enormous sums to collectors.",
    personality: "Methodical",
    weight: 45,
    height: 0.8,
    captureRate: 50,
    evolutionFromId: "prism-gecko",
    evolutionToId: null,
    evolutionLevel: null,
    skills: [
      { name: "Crystal Claw", type: "normal", element: "Crystal", power: 52, accuracy: 95, description: "Slices with razor-edged crystal claws." },
      { name: "Gem Burst", type: "skill1", element: "Crystal", power: 75, accuracy: 88, description: "Launches crystal gems with explosive force." },
      { name: "Facet Shield", type: "skill2", element: "Crystal", power: 0, accuracy: 100, description: "Raises crystal facets to massively boost defense." },
      { name: "Crystal Fortress", type: "ultimate", element: "Crystal", power: 142, accuracy: 70, description: "Constructs an instant crystal fortress that then shatters outward." },
      { name: "Diamond Shell", type: "passive", element: "Crystal", power: 0, accuracy: 100, description: "Defense is considered 30% higher when calculating damage received." },
    ],
    regionIds: ["crystal-caverns"],
  },
  // ====== METAL ======
  {
    id: "iron-tortoise",
    name: "Iron Tortoise",
    element: "Metal",
    rarity: "Common",
    baseHp: 70,
    baseAttack: 45,
    baseDefense: 82,
    baseSpeed: 25,
    description: "A tortoise with a shell reinforced by living metal.",
    lore: "Iron Tortoises have been found in ancient battlefields, completely unharmed by the carnage around them. Generals have tried to use them as living shields throughout history.",
    personality: "Immovable",
    weight: 310,
    height: 0.9,
    captureRate: 78,
    evolutionFromId: null,
    evolutionToId: "steel-maw",
    evolutionLevel: 20,
    skills: [
      { name: "Metal Bash", type: "normal", element: "Metal", power: 42, accuracy: 95, description: "Bashes with an iron-reinforced head." },
      { name: "Steel Bite", type: "skill1", element: "Metal", power: 65, accuracy: 90, description: "Bites with steel teeth that pierce armor." },
      { name: "Iron Defense", type: "skill2", element: "Metal", power: 0, accuracy: 100, description: "Boosts defense to near-impenetrable levels." },
      { name: "Metal Storm", type: "ultimate", element: "Metal", power: 132, accuracy: 72, description: "Unleashes a storm of metal shards from its shell." },
      { name: "Ironclad", type: "passive", element: "Metal", power: 0, accuracy: 100, description: "Immune to critical hits." },
    ],
    regionIds: ["power-plant", "desert"],
  },
  // ====== AIR ======
  {
    id: "sky-dancer",
    name: "Sky Dancer",
    element: "Air",
    rarity: "Common",
    baseHp: 44,
    baseAttack: 55,
    baseDefense: 38,
    baseSpeed: 88,
    description: "A bird-like creature that performs aerial dances in storm clouds.",
    lore: "Sky Dancers are considered the most graceful creatures alive. Their aerial displays during mating season draw enormous audiences of both humans and other monsters.",
    personality: "Free-spirited",
    weight: 2.5,
    height: 0.6,
    captureRate: 82,
    evolutionFromId: null,
    evolutionToId: "gale-hawk",
    evolutionLevel: 16,
    skills: [
      { name: "Breeze Slash", type: "normal", element: "Air", power: 40, accuracy: 98, description: "Slashes with a razor wind blade." },
      { name: "Wind Dance", type: "skill1", element: "Air", power: 65, accuracy: 92, description: "A graceful dance that generates cutting windblades." },
      { name: "Cyclone Spin", type: "skill2", element: "Air", power: 78, accuracy: 85, description: "Spins into a miniature cyclone." },
      { name: "Sky Tempest", type: "ultimate", element: "Air", power: 130, accuracy: 73, description: "Channels sky and storm into a supreme aerial assault." },
      { name: "Wind Rider", type: "passive", element: "Air", power: 0, accuracy: 100, description: "Evasion is 15% higher than base." },
    ],
    regionIds: ["sky-islands", "thunder-valley"],
  },
  {
    id: "gale-hawk",
    name: "Gale Hawk",
    element: "Air",
    rarity: "Rare",
    baseHp: 65,
    baseAttack: 82,
    baseDefense: 55,
    baseSpeed: 105,
    description: "A hawk that rides hurricane winds with perfect control.",
    lore: "Gale Hawks are faster than any other known creature in flight. They circle hurricane eyes, feeding on the electrical energy within. Sailors fear seeing one alone at sea.",
    personality: "Bold",
    weight: 9,
    height: 1.0,
    captureRate: 28,
    evolutionFromId: "sky-dancer",
    evolutionToId: null,
    evolutionLevel: null,
    skills: [
      { name: "Gale Slash", type: "normal", element: "Air", power: 55, accuracy: 95, description: "Slashes with a gale-force wind blade." },
      { name: "Hurricane Strike", type: "skill1", element: "Air", power: 82, accuracy: 87, description: "Strikes with the power of a hurricane." },
      { name: "Vortex Dive", type: "skill2", element: "Air", power: 95, accuracy: 80, description: "Dives in a vortex spin at extreme speed." },
      { name: "Eye of the Storm", type: "ultimate", element: "Air", power: 168, accuracy: 65, description: "Becomes the eye of a concentrated storm and releases it all." },
      { name: "Tailwind", type: "passive", element: "Air", power: 0, accuracy: 100, description: "Always acts first when speed is tied. Breaks speed ties definitively." },
    ],
    regionIds: ["sky-islands"],
  },
  // ====== LEGENDARY ======
  {
    id: "celestial-drake",
    name: "Celestial Drake",
    element: "Light",
    rarity: "Legendary",
    baseHp: 130,
    baseAttack: 128,
    baseDefense: 115,
    baseSpeed: 88,
    description: "A drake that exists at the boundary between the world and the cosmos.",
    lore: "Celestial Drakes are spoken of only in ancient texts. They do not age, they do not need to eat, and they have witnessed the rise and fall of civilizations. Meeting one is said to change a person fundamentally.",
    personality: "Transcendent",
    weight: 0,
    height: 12.0,
    captureRate: 2,
    evolutionFromId: null,
    evolutionToId: null,
    evolutionLevel: null,
    skills: [
      { name: "Stellar Claw", type: "normal", element: "Light", power: 80, accuracy: 93, description: "Claws infused with stellar matter." },
      { name: "Celestial Beam", type: "skill1", element: "Light", power: 115, accuracy: 82, description: "A beam of pure cosmic light." },
      { name: "Comet Strike", type: "skill2", element: "Light", power: 130, accuracy: 75, description: "Channels the impact of a comet." },
      { name: "Big Bang", type: "ultimate", element: "Void", power: 240, accuracy: 52, description: "Recreates the moment of cosmic creation." },
      { name: "Cosmic Aura", type: "passive", element: "Light", power: 0, accuracy: 100, description: "All stats are 20% higher. Cannot be debuffed." },
    ],
    regionIds: ["ancient-temple", "sky-islands"],
  },
  {
    id: "rift-sentinel",
    name: "Rift Sentinel",
    element: "Void",
    rarity: "Ancient",
    baseHp: 145,
    baseAttack: 140,
    baseDefense: 130,
    baseSpeed: 75,
    description: "An ancient guardian that maintains the boundary between dimensions.",
    lore: "The Rift Sentinel has existed since before the world was formed. It patrols the cracks between dimensions, ensuring nothing escapes or enters that should not. Scholars debate whether it is a monster or something else entirely.",
    personality: "Unknowable",
    weight: 0,
    height: 0,
    captureRate: 1,
    evolutionFromId: null,
    evolutionToId: null,
    evolutionLevel: null,
    skills: [
      { name: "Rift Slash", type: "normal", element: "Void", power: 88, accuracy: 92, description: "Slashes through the fabric of reality." },
      { name: "Dimensional Collapse", type: "skill1", element: "Void", power: 125, accuracy: 80, description: "Collapses a local dimension onto the target." },
      { name: "Entropy Field", type: "skill2", element: "Void", power: 138, accuracy: 72, description: "Creates a field where entropy is maximized." },
      { name: "Universal Reset", type: "ultimate", element: "Void", power: 280, accuracy: 45, description: "Resets all existence in a local area to void." },
      { name: "Dimension Lock", type: "passive", element: "Void", power: 0, accuracy: 100, description: "Cannot be affected by status effects or stat changes." },
    ],
    regionIds: ["ancient-temple"],
  },
];
