import type { InsertRegion } from "@workspace/db";

export const REGION_SEED_DATA: InsertRegion[] = [
  {
    id: "verdant-meadows",
    name: "Verdant Meadows",
    biome: "Meadow",
    description: "A lush park surrounded by ancient trees. The main gathering ground for new myth hunters.",
    requiredExplorerLevel: 1,
    width: 50,
    height: 50,
    monsterSpeciesIds: [
      "seed-sprite", "leaf-ferret", "vine-pup", "moss-crab", "petal-bee",
      "root-mole", "fern-hatchling", "sprout-sprite",
      "bloom-guardian", "grove-hawk",
    ],
  },
  {
    id: "volcanic-rift",
    name: "Volcanic Rift",
    biome: "Volcano",
    description: "Scorched rock, lava vents, and eternal heat. Fire myths thrive here.",
    requiredExplorerLevel: 5,
    width: 50,
    height: 50,
    monsterSpeciesIds: [
      "cinder-pup", "flame-wisp", "ash-lizard", "ember-crab", "scorch-moth",
      "pyro-toad", "torch-kit", "blaze-sprite",
      "magmar-wolf", "inferno-bat", "lava-serpent", "char-wyvern",
    ],
  },
  {
    id: "scorched-wastes",
    name: "Scorched Wastes",
    biome: "Wasteland",
    description: "Ancient lava fields cooled to obsidian flatlands. Rare fire myths roam here.",
    requiredExplorerLevel: 10,
    width: 50,
    height: 50,
    monsterSpeciesIds: [
      "cinder-pup", "ash-lizard", "torch-kit", "blaze-sprite",
      "forge-golem", "scorched-mantis", "lava-serpent",
      "volcanus", "pyro-titan", "magma-basilisk", "cinder-phoenix",
    ],
  },
  {
    id: "ocean-ruins",
    name: "Ocean Ruins",
    biome: "Coastal",
    description: "A sunken ancient city at the ocean's edge. Tides wash over crumbling monuments.",
    requiredExplorerLevel: 5,
    width: 50,
    height: 50,
    monsterSpeciesIds: [
      "tide-pup", "coral-sprite", "brook-turtle", "wave-imp", "reef-hatchling",
      "surge-hound", "sea-golem", "aqua-guardian", "storm-crab",
    ],
  },
  {
    id: "deep-current",
    name: "Deep Current",
    biome: "Ocean Trench",
    description: "The deep ocean floor where sunlight never reaches. Ancient water myths dwell here.",
    requiredExplorerLevel: 15,
    width: 50,
    height: 50,
    monsterSpeciesIds: [
      "mist-jellyfish", "stream-otter", "puddle-toad",
      "deep-ray", "abyssal-eel",
      "tempest-leviathan", "ocean-titan", "tide-colossus", "abyss-wyrm",
      "poseidon-serpent", "thalassa-deity",
    ],
  },
  {
    id: "ancient-forest",
    name: "Ancient Forest",
    biome: "Forest",
    description: "A forest where every tree is older than recorded civilization. Something watches.",
    requiredExplorerLevel: 10,
    width: 50,
    height: 50,
    monsterSpeciesIds: [
      "seed-sprite", "leaf-ferret", "vine-pup", "fern-hatchling",
      "bloom-guardian", "thorn-wolf", "briar-golem", "spore-bat", "canopy-serpent",
      "ancient-treant", "verdant-titan", "thorn-colossus", "gaia-wyrm",
    ],
  },
  {
    id: "thunder-valley",
    name: "Thunder Valley",
    biome: "Storm Plains",
    description: "Lightning strikes the earth thousands of times per day. Electric myths evolved here.",
    requiredExplorerLevel: 8,
    width: 50,
    height: 50,
    monsterSpeciesIds: [
      "spark-kit", "zap-moth", "volt-hatchling", "arc-sprite",
      "static-crab", "buzz-bee", "jolt-lizard", "charge-pup",
      "thunder-wolf", "storm-bat", "storm-serpent", "arc-golem", "lightning-hawk",
    ],
  },
  {
    id: "storm-peaks",
    name: "Storm Peaks",
    biome: "Mountain Storm",
    description: "Mountain peaks permanently wrapped in electrical storms. The most powerful electric myths dwell at the summit.",
    requiredExplorerLevel: 18,
    width: 45,
    height: 45,
    monsterSpeciesIds: [
      "volt-hatchling", "static-crab", "jolt-lizard",
      "plasma-ray", "storm-serpent",
      "storm-colossus", "galvanos", "tempest-titan", "arc-leviathan",
      "zeus-wyrm", "thunder-deity",
    ],
  },
  {
    id: "shadow-marsh",
    name: "Shadow Marsh",
    biome: "Dark Marsh",
    description: "Sunlight has never reached the marsh floor. Dark myths hunt in the permanent twilight.",
    requiredExplorerLevel: 8,
    width: 50,
    height: 50,
    monsterSpeciesIds: [
      "shadow-imp", "gloom-wisp", "dusk-ferret", "night-crab",
      "umbra-moth", "murk-toad",
      "void-stalker", "shadow-bat", "dusk-serpent", "gloom-golem", "eclipse-hawk",
    ],
  },
  {
    id: "void-realm",
    name: "Void Realm",
    biome: "Dimensional Rift",
    description: "A breach between dimensions where the most powerful dark myths phase in and out of existence.",
    requiredExplorerLevel: 20,
    width: 40,
    height: 40,
    monsterSpeciesIds: [
      "dark-sprite", "shade-hatchling", "dusk-ferret",
      "nightmare-specter",
      "abyssal-wraith", "void-titan", "dark-colossus", "shadow-leviathan",
      "erebus-entity", "void-deity",
    ],
  },
];
