import type { InsertRegion } from "@workspace/db";

export const REGION_SEED_DATA: InsertRegion[] = [
  {
    id: "verdant-meadows",
    name: "Verdant Meadows",
    biome: "Forest",
    description: "A lush, welcoming meadow surrounded by ancient trees. The perfect starting ground for new explorers.",
    requiredExplorerLevel: 1,
    width: 50,
    height: 50,
    monsterSpeciesIds: ["leafhorn", "thorn-boar", "stoneback", "prism-gecko", "dawn-hawk", "frost-bear", "volt-lynx"],
  },
  {
    id: "volcanic-rift",
    name: "Volcanic Rift",
    biome: "Volcano",
    description: "A scarred landscape of cooling lava and steam vents. The heat here is nearly unbearable.",
    requiredExplorerLevel: 5,
    width: 50,
    height: 50,
    monsterSpeciesIds: ["ember-drake", "lava-horn", "pyro-fox", "sand-lurker", "iron-tortoise"],
  },
  {
    id: "crystal-caverns",
    name: "Crystal Caverns",
    biome: "Cave",
    description: "Underground caverns filled with bioluminescent crystals of every color. Strange energies pulse through the walls.",
    requiredExplorerLevel: 5,
    width: 40,
    height: 40,
    monsterSpeciesIds: ["prism-gecko", "facet-crab", "crystal-wolf", "frost-bear", "void-crawler"],
  },
  {
    id: "thunder-valley",
    name: "Thunder Valley",
    biome: "Storm",
    description: "A valley where lightning strikes the earth thousands of times per day. Electricity crackles in the air constantly.",
    requiredExplorerLevel: 10,
    width: 50,
    height: 50,
    monsterSpeciesIds: ["volt-lynx", "thunder-raven", "storm-eel", "sky-dancer", "gale-hawk"],
  },
  {
    id: "shadow-marsh",
    name: "Shadow Marsh",
    biome: "Marsh",
    description: "A poisonous marsh where sunlight never reaches the ground. Dark things lurk in the murky depths.",
    requiredExplorerLevel: 10,
    width: 50,
    height: 50,
    monsterSpeciesIds: ["night-stalker", "shadow-moth", "void-crawler", "aquafin", "tide-walker"],
  },
  {
    id: "ancient-temple",
    name: "Ancient Temple",
    biome: "Ruins",
    description: "The ruins of a civilization so old, no record exists of who built it. Power radiates from every stone.",
    requiredExplorerLevel: 20,
    width: 45,
    height: 45,
    monsterSpeciesIds: ["solar-wyrm", "dawn-hawk", "void-crawler", "celestial-drake", "rift-sentinel"],
  },
];
