/** Returns a large emoji that represents each myth visually in the encounter popup */
export const MONSTER_EMOJI: Record<string, string> = {
  // ── Fire ───────────────────────────────────────────────────────────────────
  'cinder-pup':       '🐶🔥',
  'flame-wisp':       '🌟🔥',
  'ash-lizard':       '🦎🌫️',
  'ember-crab':       '🦀🔥',
  'scorch-moth':      '🦋🔥',
  'pyro-toad':        '🐸🔥',
  'torch-kit':        '🦊🔥',
  'blaze-sprite':     '🧚🔥',
  'magmar-wolf':      '🐺🌋',
  'inferno-bat':      '🦇🔥',
  'lava-serpent':     '🐍🌋',
  'char-wyvern':      '🐉🔥',
  'forge-golem':      '🗿🔥',
  'scorched-mantis':  '🦗🔥',
  'volcanus':         '🦁🌋',
  'pyro-titan':       '👹🔥',
  'magma-basilisk':   '🐲🌋',
  'cinder-phoenix':   '🦅🔥',
  'ignis-seraph':     '👼🔥',
  'helios-wyrm':      '☀️🐉',

  // ── Water ──────────────────────────────────────────────────────────────────
  'tide-pup':         '🐶💧',
  'coral-sprite':     '🧚🪸',
  'mist-jellyfish':   '🪼💨',
  'brook-turtle':     '🐢💧',
  'stream-otter':     '🦦💧',
  'wave-imp':         '👺🌊',
  'puddle-toad':      '🐸💧',
  'reef-hatchling':   '🐠🪸',
  'surge-hound':      '🐕🌊',
  'deep-ray':         '🐟🌊',
  'abyssal-eel':      '🐍🌊',
  'sea-golem':        '🗿🌊',
  'aqua-guardian':    '🛡️💧',
  'storm-crab':       '🦀⛈️',
  'tempest-leviathan':'🐋⛈️',
  'ocean-titan':      '🐋🌊',
  'tide-colossus':    '🌊🗿',
  'abyss-wyrm':       '🐲🌊',
  'poseidon-serpent': '🔱🐍',
  'thalassa-deity':   '🧜💧',

  // ── Nature ─────────────────────────────────────────────────────────────────
  'seed-sprite':      '🌱🧚',
  'leaf-ferret':      '🦡🍃',
  'vine-pup':         '🐶🌿',
  'moss-crab':        '🦀🌿',
  'petal-bee':        '🐝🌸',
  'root-mole':        '🦔🌿',
  'fern-hatchling':   '🐣🌿',
  'sprout-sprite':    '🌱✨',
  'bloom-guardian':   '🌸🛡️',
  'thorn-wolf':       '🐺🌿',
  'grove-hawk':       '🦅🌿',
  'briar-golem':      '🗿🌿',
  'spore-bat':        '🦇🍄',
  'canopy-serpent':   '🐍🌿',
  'ancient-treant':   '🌳✨',
  'verdant-titan':    '🌿👹',
  'thorn-colossus':   '🗿🌵',
  'gaia-wyrm':        '🐲🌿',
  'sylvan-deity':     '🧝🌿',
  'earthmother':      '🌍✨',

  // ── Electric ───────────────────────────────────────────────────────────────
  'spark-kit':        '🐱⚡',
  'zap-moth':         '🦋⚡',
  'volt-hatchling':   '🐣⚡',
  'arc-sprite':       '🧚⚡',
  'static-crab':      '🦀⚡',
  'buzz-bee':         '🐝⚡',
  'jolt-lizard':      '🦎⚡',
  'charge-pup':       '🐶⚡',
  'thunder-wolf':     '🐺⚡',
  'storm-bat':        '🦇⚡',
  'plasma-ray':       '🐟⚡',
  'storm-serpent':    '🐍⚡',
  'arc-golem':        '🗿⚡',
  'lightning-hawk':   '🦅⚡',
  'storm-colossus':   '⛈️🗿',
  'galvanos':         '⚡🦁',
  'tempest-titan':    '⛈️👹',
  'arc-leviathan':    '⚡🐋',
  'zeus-wyrm':        '⚡🐉',
  'thunder-deity':    '⛈️👑',

  // ── Dark ───────────────────────────────────────────────────────────────────
  'shadow-imp':       '😈🌑',
  'gloom-wisp':       '🌟🌑',
  'dusk-ferret':      '🦡🌑',
  'night-crab':       '🦀🌑',
  'umbra-moth':       '🦋🌑',
  'murk-toad':        '🐸🌑',
  'dark-sprite':      '🧚🌑',
  'shade-hatchling':  '🐣🌑',
  'void-stalker':     '🐺🕳️',
  'nightmare-specter':'👻🌑',
  'shadow-bat':       '🦇🌑',
  'dusk-serpent':     '🐍🌑',
  'gloom-golem':      '🗿🌑',
  'eclipse-hawk':     '🦅🌑',
  'abyssal-wraith':   '👁️🌑',
  'void-titan':       '🌑👹',
  'dark-colossus':    '🗿🌑',
  'shadow-leviathan': '🌑🐋',
  'erebus-entity':    '🌑⭐',
  'void-deity':       '🕳️👑',
};

/** Fallback emoji by element */
export const ELEMENT_EMOJI: Record<string, string> = {
  Fire:     '🔥',
  Water:    '💧',
  Nature:   '🌿',
  Electric: '⚡',
  Dark:     '🌑',
};

export function getMonsterEmoji(id: string, element: string): string {
  return MONSTER_EMOJI[id] ?? (ELEMENT_EMOJI[element] ?? '❓');
}
