/** Returns a large emoji that represents each myth visually */
export const MONSTER_EMOJI: Record<string, string> = {
  // ── Fire ───────────────────────────────────────────────────────────────────
  'sparkub':    '🐶🔥',
  'flammi':     '🌟🔥',
  'torchip':    '🦎🔥',
  'blazibit':   '🐭🔥',
  'kindleo':    '🦊🔥',
  'seatpur':    '🐸🔥',
  'firette':    '🐦🔥',
  'emberkit':   '🐰🔥',
  'flareonix':  '🦅🔥',
  'magmaroo':   '🦘🌋',
  'cinderoar':  '🐻🔥',
  'lavabit':    '🦇🌋',
  'burnyx':     '🐱🔥',
  'pyrehorn':   '🐂🔥',
  'blazion':    '🦁🔥',
  'emberwolf':  '🐺🔥',
  'volcanix':   '🦕🌋',
  'fireclaw':   '🐉🔥',
  'pyrorax':    '🐲🌋',
  'infernix':   '🦅✨',

  // ── Water ──────────────────────────────────────────────────────────────────
  'puddleo':    '🫧💧',
  'droppi':     '💧✨',
  'fintee':     '🐟💧',
  'octazur':    '🐙💧',
  'splashy':    '🦦💧',
  'ripplowl':   '🦉🌊',
  'tinwave':    '🐢💧',
  'driplet':    '🌊✨',
  'shellion':   '🦁🌊',
  'wavenix':    '🐦🌊',
  'nereel':     '🐍🌊',
  'glaciero':   '🦭🧊',
  'bubblio':    '🐡💧',
  'kelpheon':   '🐍🌿',
  'coralux':    '🐉🪸',
  'marinel':    '🦈💧',
  'hydralisk':  '🐲🌊',
  'tidalor':    '🐉🌊',
  'aquarion':   '🌊👑',
  'leviaqua':   '🐋🌊',

  // ── Nature ─────────────────────────────────────────────────────────────────
  'leaflet':    '🍃✨',
  'sprouti':    '🌱💚',
  'buddle':     '🌸🌿',
  'mossy':      '🐢🌿',
  'brambix':    '🦔🌿',
  'cloverit':   '🐰🍀',
  'twiglet':    '🪲🌿',
  'fernkit':    '🌿✨',
  'vinegor':    '🐗🌿',
  'bloombo':    '🐼🌸',
  'thornbel':   '🍄🌿',
  'fernix':     '🦊🌿',
  'seedleaf':   '🐢🌱',
  'grasspin':   '🐺🌾',
  'leafenix':   '🦅🍃',
  'mossfern':   '🗿🌿',
  'rootora':    '🐲🌿',
  'wildbud':    '🐆🌸',
  'verdantis':  '🌳👑',
  'florazar':   '🌺✨',

  // ── Electric ───────────────────────────────────────────────────────────────
  'zaplet':     '🐦⚡',
  'zipbee':     '🐝⚡',
  'electrix':   '🦀⚡',
  'boltin':     '🐗⚡',
  'sparkit':    '🐱⚡',
  'wattspy':    '🦎⚡',
  'charglet':   '🐹⚡',
  'voltspark':  '🐱⚡',
  'voltyk':     '🦅⚡',
  'shockip':    '🦎⚡',
  'amphare':    '🐊⚡',
  'elekio':     '🦦⚡',
  'joltoll':    '👹⚡',
  'statichu':   '🐭⚡',
  'sparko':     '🐺⚡',
  'lumirae':    '🐉🌈',
  'chargeon':   '🦏⚡',
  'thundkit':   '🦊⚡',
  'zapdrix':    '🐲⚡',
  'voltiger':   '🐯⚡',

  // ── Dark ───────────────────────────────────────────────────────────────────
  'darkit':     '🐱🌑',
  'inko':       '🐙🌑',
  'shadeek':    '🦔🌑',
  'gloombat':   '🦇🌑',
  'nyxie':      '🧚🌑',
  'scuppi':     '🐶🌑',
  'wispurr':    '👻🌑',
  'shadowpup':  '🐕🌑',
  'grimclaw':   '🐆🌑',
  'nightfang':  '🐍🌑',
  'spectrix':   '🦊🌑',
  'dreadimp':   '😈🌑',
  'eclipseer':  '👁️🌑',
  'murkrowl':   '🦅🌑',
  'shadowlurk': '🐺🌑',
  'duskhowl':   '🐺🌙',
  'maligno':    '🐲🌑',
  'voidraven':  '🦅🕳️',
  'umbraeon':   '🌑👑',
  'noctiris':   '🐍✨',
};

/** Fallback emoji by element */
export const ELEMENT_EMOJI: Record<string, string> = {
  Fire:     '🔥',
  Water:    '💧',
  Nature:   '🌿',
  Electric: '⚡',
  Dark:     '🌑',
};

export function getMonsterEmoji(id: string, element: string): string {
  return MONSTER_EMOJI[id] ?? (ELEMENT_EMOJI[element] ?? '❓');
}
